[features]
seeds = false
[programs.localnet]
cronos_dca = "H8LECSL9wE5HVVs1jAYoixq1MBsvoiRVrCvfiTbRA8Xo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/jay/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
